# 5. projekt do predmetu ITY
# autor: Roman Halik
# login: xhalik01

FILE=proj5

all: 
	vlna -l -v KkSsVvZzOoUuAaIi $(FILE).tex
	latex $(FILE).tex
	latex $(FILE).tex
	dvips -t a4 $(FILE).dvi
	ps2pdf $(FILE).ps

