//<!--
var bAgentExplorer4 = (navigator.appVersion.substring(0,1) >= "4");
if ((bAgentExplorer4)) {
today = new Date();
den=today.getDate();
mesic=(today.getMonth()+1);
if (mesic==1) {
if (den==01) jmeno="Nový rok";
if (den==02) jmeno="Karina";
if (den==03) jmeno="Radmila";
if (den==04) jmeno="Diana";
if (den==05) jmeno="Dalimil";
if (den==06) jmeno="Kašpar, Melichar a Baltazar";
if (den==07) jmeno="Vilma";
if (den==08) jmeno="Èestmír";
if (den==09) jmeno="Vladan";
if (den==10) jmeno="Bøetislav";
if (den==11) jmeno="Bohdana";
if (den==12) jmeno="Pravoslav";
if (den==13) jmeno="Edita";
if (den==14) jmeno="Radovan";
if (den==15) jmeno="Alice";
if (den==16) jmeno="Ctirad";
if (den==17) jmeno="Drahoslav";
if (den==18) jmeno="Vladislav";
if (den==19) jmeno="Doubravka";
if (den==20) jmeno="Ilona";
if (den==21) jmeno="Bìla";
if (den==22) jmeno="Slavomír";
if (den==23) jmeno="Zdenìk";
if (den==24) jmeno="Milena";
if (den==25) jmeno="Miloš";
if (den==26) jmeno="Zora";
if (den==27) jmeno="Ingrid";
if (den==28) jmeno="Otýlie";
if (den==29) jmeno="Zdislava";
if (den==30) jmeno="Robin";
if (den==31) jmeno="Marika";
}
if (mesic==2) {
if (den==01) jmeno="Hynek";
if (den==02) jmeno="Nela";
if (den==03) jmeno="Blažej";
if (den==04) jmeno="Jarmila";
if (den==05) jmeno="Dobromila";
if (den==06) jmeno="Vanda";
if (den==07) jmeno="Veronika";
if (den==08) jmeno="Milada";
if (den==09) jmeno="Apolena";
if (den==10) jmeno="Mojmír";
if (den==11) jmeno="Božena";
if (den==12) jmeno="Slavìna";
if (den==13) jmeno="Vìnceslav";
if (den==14) jmeno="Valentýn";
if (den==15) jmeno="Jiøina";
if (den==16) jmeno="Ljuba";
if (den==17) jmeno="Miloslava";
if (den==18) jmeno="Gizela";
if (den==19) jmeno="Patrik";
if (den==20) jmeno="Oldøich";
if (den==21) jmeno="Lenka";
if (den==22) jmeno="Petr";
if (den==23) jmeno="Svatopluk";
if (den==24) jmeno="Matìj";
if (den==25) jmeno="Liliana";
if (den==26) jmeno="Dorota";
if (den==27) jmeno="Alexandr";
if (den==28) jmeno="Lumír";
if (den==29) jmeno="";
}
if (mesic==3) {
if (den==01) jmeno="Bedøich";
if (den==02) jmeno="Anežka";
if (den==03) jmeno="Kamil";
if (den==04) jmeno="Stela";
if (den==05) jmeno="Kazimir";
if (den==06) jmeno="Miroslav";
if (den==07) jmeno="Tomáš";
if (den==08) jmeno="Gabriela";
if (den==09) jmeno="Františka";
if (den==10) jmeno="Viktorie";
if (den==11) jmeno="Andìla";
if (den==12) jmeno="Øehoø";
if (den==13) jmeno="Rùžena";
if (den==14) jmeno="Rùt a Matylda";
if (den==15) jmeno="Ida";
if (den==16) jmeno="Elena a Herbert";
if (den==17) jmeno="Vlastimil";
if (den==18) jmeno="Eduard";
if (den==19) jmeno="Josef";
if (den==20) jmeno="Svìtlana";
if (den==21) jmeno="Radek";
if (den==22) jmeno="Leona";
if (den==23) jmeno="Ivona";
if (den==24) jmeno="Gabriel";
if (den==25) jmeno="Marian";
if (den==26) jmeno="Emanuel";
if (den==27) jmeno="Dita";
if (den==28) jmeno="Soòa";
if (den==29) jmeno="Taána";
if (den==30) jmeno="Arnošt";
if (den==31) jmeno="Kvido";
}
if (mesic==4) {
if (den==01) jmeno="Hugo";
if (den==02) jmeno="Erika";
if (den==03) jmeno="Richard";
if (den==04) jmeno="Ivana";
if (den==05) jmeno="Miroslava";
if (den==06) jmeno="Vendula";
if (den==07) jmeno="Heøman a Hermína";
if (den==08) jmeno="Ema";
if (den==09) jmeno="Dušan";
if (den==10) jmeno="Darja";
if (den==11) jmeno="Izabela";
if (den==12) jmeno="Julius";
if (den==13) jmeno="Aleš";
if (den==14) jmeno="Vincenc";
if (den==15) jmeno="Anastázie";
if (den==16) jmeno="Irena";
if (den==17) jmeno="Rudolf";
if (den==18) jmeno="Valérie";
if (den==19) jmeno="Rostislav";
if (den==20) jmeno="Marcela";
if (den==21) jmeno="Alexandra";
if (den==22) jmeno="Evženie";
if (den==23) jmeno="Vojtìch";
if (den==24) jmeno="Jiøí";
if (den==25) jmeno="Marek";
if (den==26) jmeno="Oto";
if (den==27) jmeno="Jaroslav";
if (den==28) jmeno="Vlastislav";
if (den==29) jmeno="Robert";
if (den==30) jmeno="Blahoslav";
}
if (mesic==5) {
if (den==01) jmeno=" ";
if (den==02) jmeno="Zikmund";
if (den==03) jmeno="Alexej";
if (den==04) jmeno="Kvìtoslav";
if (den==05) jmeno="Klaudie";
if (den==06) jmeno="Radoslav";
if (den==07) jmeno="Stanislav";
if (den==08) jmeno=" ";
if (den==09) jmeno="Ctibor";
if (den==10) jmeno="Blažena";
if (den==11) jmeno="Svatava";
if (den==12) jmeno="Pankrác";
if (den==13) jmeno="Servác";
if (den==14) jmeno="Bonifác";
if (den==15) jmeno="Žofie";
if (den==16) jmeno="Pøemysl";
if (den==17) jmeno="Aneta";
if (den==18) jmeno="Nataša";
if (den==19) jmeno="Ivo";
if (den==20) jmeno="Zbyšek";
if (den==21) jmeno="Monika";
if (den==22) jmeno="Emil";
if (den==23) jmeno="Vladimír";
if (den==24) jmeno="Jana";
if (den==25) jmeno="Viola";
if (den==26) jmeno="Filip";
if (den==27) jmeno="Valdemar";
if (den==28) jmeno="Vilém";
if (den==29) jmeno="Maxmilián";
if (den==30) jmeno="Ferdinand";
if (den==31) jmeno="Kamila";
}
if (mesic==6) {
if (den==01) jmeno="Laura";
if (den==02) jmeno="Jarmil";
if (den==03) jmeno="Tamara";
if (den==04) jmeno="Dalibor";
if (den==05) jmeno="Dobroslav";
if (den==06) jmeno="Norbert";
if (den==07) jmeno="Iveta a Slavoj";
if (den==08) jmeno="Medard";
if (den==09) jmeno="Stanislava";
if (den==10) jmeno="Gita";
if (den==11) jmeno="Bruno";
if (den==12) jmeno="Antonie";
if (den==13) jmeno="Antonín";
if (den==14) jmeno="Roland";
if (den==15) jmeno="Vít";
if (den==16) jmeno="Zbynìk";
if (den==17) jmeno="Adolf";
if (den==18) jmeno="Milan";
if (den==19) jmeno="Leoš";
if (den==20) jmeno="Kvìta";
if (den==21) jmeno="Alois";
if (den==22) jmeno="Pavla";
if (den==23) jmeno="Zdeòka";
if (den==24) jmeno="Jan";
if (den==25) jmeno="Ivan";
if (den==26) jmeno="Adriana";
if (den==27) jmeno="Ladislav";
if (den==28) jmeno="Lubomír";
if (den==29) jmeno="Petr a Pavel";
if (den==30) jmeno="Šárka";
}
if (mesic==7) {
if (den==01) jmeno="Jaroslava";
if (den==02) jmeno="Patricie";
if (den==03) jmeno="Radomír";
if (den==04) jmeno="Prokop";
if (den==05) jmeno=" ";
if (den==06) jmeno=" ";
if (den==07) jmeno="Bohuslava";
if (den==08) jmeno="Nora";
if (den==09) jmeno="Drahoslava";
if (den==10) jmeno="Libuše a Amálie";
if (den==11) jmeno="Olga";
if (den==12) jmeno="Boøek";
if (den==13) jmeno="Markéta";
if (den==14) jmeno="Karolína";
if (den==15) jmeno="Jindøich";
if (den==16) jmeno="Luboš";
if (den==17) jmeno="Martina";
if (den==18) jmeno="Drahomíra";
if (den==19) jmeno="Èenìk";
if (den==20) jmeno="Ilja";
if (den==21) jmeno="Vítìzslav";
if (den==22) jmeno="Magdaléna";
if (den==23) jmeno="Libor";
if (den==24) jmeno="Kristýna";
if (den==25) jmeno="Jakub";
if (den==26) jmeno="Anna";
if (den==27) jmeno="Vìroslav";
if (den==28) jmeno="Viktor";
if (den==29) jmeno="Marta";
if (den==30) jmeno="Boøivoj";
if (den==31) jmeno="Ignác";
}
if (mesic==8) {
if (den==01) jmeno="Oskar";
if (den==02) jmeno="Gustav";
if (den==03) jmeno="Miluše";
if (den==04) jmeno="Dominik";
if (den==05) jmeno="Kristian";
if (den==06) jmeno="Oldøiška";
if (den==07) jmeno="Lada";
if (den==08) jmeno="Sobìslav";
if (den==09) jmeno="Roman";
if (den==10) jmeno="Vavøinec";
if (den==11) jmeno="Zuzana";
if (den==12) jmeno="Klára";
if (den==13) jmeno="Alena";
if (den==14) jmeno="Alan";
if (den==15) jmeno="Hana";
if (den==16) jmeno="Jáchym";
if (den==17) jmeno="Petra";
if (den==18) jmeno="Helena";
if (den==19) jmeno="Ludvík";
if (den==20) jmeno="Bernard";
if (den==21) jmeno="Johana";
if (den==22) jmeno="Bohuslav";
if (den==23) jmeno="Sandra";
if (den==24) jmeno="Bartolomìj";
if (den==25) jmeno="Radim";
if (den==26) jmeno="Ludìk";
if (den==27) jmeno="Otakar";
if (den==28) jmeno="Augustýn";
if (den==29) jmeno="Evelína";
if (den==30) jmeno="Vladìna";
if (den==31) jmeno="Pavlína";
}
if (mesic==9) {
if (den==01) jmeno="Linda a Samuel";
if (den==02) jmeno="Adéla";
if (den==03) jmeno="Bronislav";
if (den==04) jmeno="Jindøiška";
if (den==05) jmeno="Boris";
if (den==06) jmeno="Boleslav";
if (den==07) jmeno="Regína";
if (den==08) jmeno="Mariana";
if (den==09) jmeno="Daniela";
if (den==10) jmeno="Irma";
if (den==11) jmeno="Denisa";
if (den==12) jmeno="Marie";
if (den==13) jmeno="Lubor";
if (den==14) jmeno="Radka";
if (den==15) jmeno="Jolana";
if (den==16) jmeno="Ludmila";
if (den==17) jmeno="Nadìžda";
if (den==18) jmeno="Kryštof";
if (den==19) jmeno="Zita";
if (den==20) jmeno="Oleg";
if (den==21) jmeno="Matouš";
if (den==22) jmeno="Darina";
if (den==23) jmeno="Berta";
if (den==24) jmeno="Jaromír";
if (den==25) jmeno="Zlata";
if (den==26) jmeno="Andrea";
if (den==27) jmeno="Jonáš";
if (den==28) jmeno="Václav";
if (den==29) jmeno="Michal";
if (den==30) jmeno="Jeroným";

}
if (mesic==10) {
if (den==01) jmeno="Igor";
if (den==02) jmeno="Olivie a Oliver";
if (den==03) jmeno="Bohumil";
if (den==04) jmeno="František";
if (den==05) jmeno="Eliška";
if (den==06) jmeno="Hanuš";
if (den==07) jmeno="Justýna";
if (den==08) jmeno="Vìra";
if (den==09) jmeno="Štefan a Sára";
if (den==10) jmeno="Marina";
if (den==11) jmeno="Andrej";
if (den==12) jmeno="Marcel";
if (den==13) jmeno="Renáta";
if (den==14) jmeno="Agáta";
if (den==15) jmeno="Tereza";
if (den==16) jmeno="Havel";
if (den==17) jmeno="Hedvika";
if (den==18) jmeno="Lukáš";
if (den==19) jmeno="Michaela";
if (den==20) jmeno="Vendelín";
if (den==21) jmeno="Brigita";
if (den==22) jmeno="Sabina";
if (den==23) jmeno="Teodor";
if (den==24) jmeno="Nina";
if (den==25) jmeno="Beáta";
if (den==26) jmeno="Erik";
if (den==27) jmeno="Šarlota a Zoe";
if (den==28) jmeno=" ";
if (den==29) jmeno="Silvie";
if (den==30) jmeno="Tadeáš";
if (den==31) jmeno="Štìpánka";
}
if (mesic==11) {
if (den==01) jmeno="Felix";
if (den==02) jmeno=" ";
if (den==03) jmeno="Hubert";
if (den==04) jmeno="Karel";
if (den==05) jmeno="Miriam";
if (den==06) jmeno="Libìna";
if (den==07) jmeno="Saskie";
if (den==08) jmeno="Bohumír";
if (den==09) jmeno="Bohdan";
if (den==10) jmeno="Evžen";
if (den==11) jmeno="Martin";
if (den==12) jmeno="Benedikt";
if (den==13) jmeno="Tibor";
if (den==14) jmeno="Sáva";
if (den==15) jmeno="Leopold";
if (den==16) jmeno="Otmar";
if (den==17) jmeno="Mahulena";
if (den==18) jmeno="Romana";
if (den==19) jmeno="Alžbìta";
if (den==20) jmeno="Nikola";
if (den==21) jmeno="Albert";
if (den==22) jmeno="Cecílie";
if (den==23) jmeno="Klement";
if (den==24) jmeno="Emílie";
if (den==25) jmeno="Kateøina";
if (den==26) jmeno="Artur";
if (den==27) jmeno="Xenie";
if (den==28) jmeno="René";
if (den==29) jmeno="Zina";
if (den==30) jmeno="Ondøej";
}
if (mesic==12) {
if (den==01) jmeno="Iva";
if (den==02) jmeno="Blanka";
if (den==03) jmeno="Svatoslav";
if (den==04) jmeno="Barbora";
if (den==05) jmeno="Jitka";
if (den==06) jmeno="Mikuláš";
if (den==07) jmeno="Ambrož a Benjamín";
if (den==08) jmeno="Kvìtoslava";
if (den==09) jmeno="Vratislav";
if (den==10) jmeno="Julie";
if (den==11) jmeno="Dana";
if (den==12) jmeno="Simona";
if (den==13) jmeno="Lucie";
if (den==14) jmeno="Lýdie";
if (den==15) jmeno="Radana a Radan";
if (den==16) jmeno="Albína";
if (den==17) jmeno="Daniel";
if (den==18) jmeno="Miloslav";
if (den==19) jmeno="Ester";
if (den==20) jmeno="Dagmar";
if (den==21) jmeno="Natálie";
if (den==22) jmeno="Šimon";
if (den==23) jmeno="Vlasta";
if (den==24) jmeno="Adam a Eva";
if (den==25) jmeno=" ";
if (den==26) jmeno="Štìpán";
if (den==27) jmeno="Žaneta";
if (den==28) jmeno="Bohumila";
if (den==29) jmeno="Judita";
if (den==30) jmeno="David";
if (den==31) jmeno="Silvestr";
}
document.write("Svátek má " + jmeno);
}
//-->